apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "veritrace.fullname" . }}
  labels: {{- include "veritrace.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "veritrace.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "veritrace.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
            {{- if .Values.otel.endpoint }}
            - name: VT_OTEL_ENDPOINT
              value: "{{ .Values.otel.endpoint }}"
            {{- end }}
          readinessProbe:
            httpGet: { path: /health/ready, port: {{ .Values.service.port }} }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: {{ .Values.service.port }} }
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{- toYaml .Values.resources | nindent 12 }}
