"""
veritrace.cli
=============
``veritrace`` CLI - project bootstrap, config validation, and quick testing.

Commands
--------
veritrace init          Generate .env and starter veritrace_config.py in the
                        current directory.
veritrace validate      Check configuration and connectivity to Redis/Postgres.
veritrace test-inject   Run built-in injection detection against a prompt.
veritrace redteam       Run the built-in prompt-injection benchmark.
veritrace version       Print version.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys


def cmd_init(args) -> int:
    import os, secrets, textwrap
    cwd = os.getcwd()

    # .env
    env_path = os.path.join(cwd, ".env")
    if os.path.exists(env_path) and not args.force:
        print(f"  [skip] {env_path} already exists (use --force to overwrite)")
    else:
        api_key     = secrets.token_hex(32)
        signing_key = secrets.token_hex(32)
        jwt_secret  = secrets.token_hex(32)
        pg_pass     = secrets.token_hex(16)
        redis_pass  = secrets.token_hex(16)

        env_content = textwrap.dedent(f"""\
            # Generated by `veritrace init`
            VT_API_KEY={api_key}
            VT_SIGNING_KEY={signing_key}
            VT_JWT_SECRET={jwt_secret}
            POSTGRES_PASSWORD={pg_pass}
            REDIS_PASSWORD={redis_pass}
            VT_POSTGRES_DSN=postgresql://veritrace:{pg_pass}@localhost/veritrace
            VT_REDIS_URL=redis://:{redis_pass}@localhost:6379/0
            VT_LOG_LEVEL=info
            VT_MAX_INPUT_BYTES=65536
            VT_RATE_LIMIT_CAPACITY=100
            VT_RATE_LIMIT_REFILL=10
            # Optional - fill in for HITL Slack integration
            VT_HITL_SLACK_TOKEN=
            VT_HITL_SLACK_CHANNEL=
            # Optional - fill in for OpenTelemetry
            VT_OTEL_ENDPOINT=
            # Optional - usage analytics / billing webhook
            VT_BILLING_WEBHOOK_URL=
            VT_BILLING_WEBHOOK_SECRET=
            VT_BILLING_WEBHOOK_TIMEOUT_S=2.0
        """)
        with open(env_path, "w") as f:
            f.write(env_content)
        print(f"  [ok] {env_path}")

    # starter config
    cfg_path = os.path.join(cwd, "veritrace_config.py")
    if os.path.exists(cfg_path) and not args.force:
        print(f"  [skip] {cfg_path} already exists (use --force to overwrite)")
    else:
        cfg_content = textwrap.dedent("""\
            \"\"\"
            Veritrace starter configuration.
            Edit this file to customise your trust pipeline.
            \"\"\"
            from veritrace import Veritrace
            from veritrace.config import settings
            from veritrace.layers import ToolGuardLayer, ToolPolicy
            from veritrace.layers.tool_guard import SideEffect
            from veritrace.types import Verdict

            def build_armor() -> Veritrace:
                guard = ToolGuardLayer(
                    policies=[
                        # Add your tools here
                        # ToolPolicy(
                        #     name="my_tool",
                        #     side_effect=SideEffect.READ,
                        #     schema={"type": "object", "properties": {...}},
                        # ),
                    ],
                    default_verdict=Verdict.BLOCK,
                )

                backend = settings.redis_backend()   # None if Redis not configured
                store   = settings.postgres_store()  # None if Postgres not configured

                return Veritrace(
                    tool_guard=guard,
                    store=store or None,
                    audit=store or None,
                )

            armor = build_armor()
        """)
        with open(cfg_path, "w") as f:
            f.write(cfg_content)
        print(f"  [ok] {cfg_path}")

    print("\nNext steps:")
    print("  1. Edit .env (secrets are pre-generated)")
    print("  2. Edit veritrace_config.py to register your tools")
    print("  3. From the Veritrace repo root, run: docker compose up -d")
    print("  4. veritrace validate")
    return 0


def cmd_validate(args) -> int:
    from .config import Settings
    cfg = Settings()
    warnings = cfg.validate()

    print(f"Configuration: {cfg}")
    if warnings:
        for w in warnings:
            print(f"  [warn] {w}")
    else:
        print("  [ok] all configuration checks passed")

    # Redis connectivity
    if cfg.redis_url:
        try:
            from .backends.redis_backend import RedisBackend
            b = RedisBackend.from_url(cfg.redis_url)
            ok = b.ping()
            print(f"  {'[ok]' if ok else '[fail]'} Redis: {'reachable' if ok else 'unreachable'}")
        except Exception as exc:
            print(f"  [fail] Redis: {exc}")
    else:
        print("  [-] Redis: not configured (VT_REDIS_URL not set)")

    # Postgres connectivity
    if cfg.postgres_dsn:
        try:
            from .store_postgres import PostgresStore, PostgresUnavailable
            PostgresStore.from_dsn(cfg.postgres_dsn, max_pool_size=1)
            print("  [ok] Postgres: reachable, DDL applied")
        except Exception as exc:
            print(f"  [fail] Postgres: {exc}")
    else:
        print("  [-] Postgres: not configured (VT_POSTGRES_DSN not set)")

    return 1 if warnings else 0


def cmd_test_inject(args) -> int:
    prompt = args.prompt or input("Enter prompt to test: ")
    from .layers import IsolationLayer
    from .classifier import build_classifier
    from .layers.isolation import InjectionSuspected

    iso = IsolationLayer(
        classifier=build_classifier(force_keyword_only=not args.embedding),
        block_on_injection=False,
    )

    result = asyncio.run(iso.evaluate_input(prompt, tenant_id="cli", session_id="test"))

    hits = result.get("injection_hits", [])
    clf_flagged = result.get("classifier_flagged", False)

    if hits or clf_flagged:
        print("[warn] INJECTION SUSPECTED")
        for h in hits:
            print(f"   pattern: {h['pattern_id']} - {h['detail']}")
        if clf_flagged:
            print("   classifier: flagged")
    else:
        print("[ok] No injection detected")

    return 0


def cmd_redteam(args) -> int:
    from .redteam import run_injection_benchmark

    report = run_injection_benchmark(force_keyword_only=not args.embedding)
    data = report.to_dict()

    if args.json:
        print(json.dumps(data, indent=2, sort_keys=True))
    else:
        print("Veritrace prompt-injection benchmark")
        print(f"  attacks:          {report.attacks_caught}/{report.attacks_total} caught")
        print(f"  bypass rate:      {report.bypass_rate:.1%}")
        print(f"  benign prompts:   {report.benign_total}")
        print(
            "  false positives:  "
            f"{report.false_positives} ({report.false_positive_rate:.1%})"
        )
        if report.bypassed_prompts:
            print("  bypassed prompts:")
            for prompt in report.bypassed_prompts:
                print(f"    - {prompt}")

    return 1 if report.bypass_rate > args.max_bypass_rate else 0


def cmd_version(args) -> int:
    try:
        from . import __version__
        v = __version__
    except Exception:
        try:
            from importlib.metadata import version
            v = version("veritrace")
        except Exception:
            v = "dev"
    print(f"veritrace {v}")
    return 0


def main():
    parser = argparse.ArgumentParser(
        prog="veritrace",
        description="Veritrace - AI agent trust middleware",
    )
    sub = parser.add_subparsers(dest="command")

    p_init = sub.add_parser("init", help="Bootstrap a new Veritrace project")
    p_init.add_argument("--force", action="store_true",
                        help="Overwrite existing files")

    sub.add_parser("validate", help="Validate config and connectivity")

    p_inj = sub.add_parser("test-inject", help="Test injection detection on a prompt")
    p_inj.add_argument("prompt", nargs="?", default="",
                       help="Prompt to test (reads from stdin if omitted)")
    p_inj.add_argument("--embedding", action="store_true",
                       help="Use embedding classifier (requires sentence-transformers)")

    p_redteam = sub.add_parser(
        "redteam",
        help="Run built-in prompt-injection benchmark",
    )
    p_redteam.add_argument(
        "--embedding",
        action="store_true",
        help="Use embedding classifier (requires sentence-transformers)",
    )
    p_redteam.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON",
    )
    p_redteam.add_argument(
        "--max-bypass-rate",
        type=float,
        default=0.30,
        help="Exit non-zero if bypass rate exceeds this fraction",
    )

    sub.add_parser("version", help="Print version")

    args = parser.parse_args()
    handlers = {
        "init":        cmd_init,
        "validate":    cmd_validate,
        "test-inject": cmd_test_inject,
        "redteam":     cmd_redteam,
        "version":     cmd_version,
    }
    if args.command not in handlers:
        parser.print_help()
        return 1
    return handlers[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
