apiVersion: v1
kind: Service
metadata:
  name: {{ include "pramagent.fullname" . }}
  labels: {{- include "pramagent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector: {{- include "pramagent.selectorLabels" . | nindent 4 }}
